on:
  push:
    branches:
      - "main"
      
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git pull
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 46.101.135.20
          username: root
          key: ${{ secrets.sshkey }}
          port: 80
          script: "cd ndi2024; git pull"
           
